server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /phpbb/www;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /app.php?$query_string;
	}

	location ~ \.(git|ht|svn|inc|config\.php)$ {
		deny all;
	}

	location ~ \.php(/|$) {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		include fastcgi_params;
		fastcgi_intercept_errors on;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_param HTTP_PROXY "";
	}
}
